version: '3'

services:
  an-bot-db: 
    image: redis:6.0-alpine
    container_name: an-bot-db
    restart: unless-stopped
    volumes:
      - db-data:/data

  an-bot:
    build: .
    image: alien-network/discord-bot:latest
    container_name: an-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config.json:/home/node/app/config.json:ro
    depends_on:
      - an-bot-db

volumes:
  db-data:
