version: '3'

services:
  an-bot:
    build: .
    image: aliennetwork/discord-bot:0.9.0
    container_name: an-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config.js:/home/node/app/config.js:ro
