version: '3'

services:
  an-bot-db: 
    image: redis:6.2.4-alpine3.13
    container_name: an-bot-db
    restart: unless-stopped
    volumes:
      - db-data:/data

  an-bot:
    build: .
    image: aliennetwork/discord-bot:0.4.0
    container_name: an-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config.js:/home/node/app/config.js:ro
    depends_on:
      - an-bot-db

volumes:
  db-data:
